name: Deploy static files to GitHub Pages

on: [workflow_dispatch, push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "analyses"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
